### ISSUE TITLE
[pytket-pyquil] ForestBackend relies on self._cache to retrieve results

### ISSUE THREAD

**Issue by isobelhooper** [CQCL/pytket-extensions#120]
ForestBackend uses `self._cache` to store two items from `.process_results()`, and relies on them being set for `.get_results()`:
* `c_bits`, the classical bits used in the quantum circuit.
* `qam`, a PyQuil Quantum Abstract Machine, which is an interface over the machine running the circuit.

This means that ForestBackend won't currently work in a workflow that has different backend instances for `process_results()` and `get_results().

`c_bits` could potentially be added to the ResultHandle, but I don't think `qam` could be - we are limited in the types we can pass in a ResultHandle.

We also can't re-derive `qam` in `get_results` because QAM objects are stateful, so creating one in a new backend instance would not have the results.

----

A better fix for ForestBackend may be to wait for a release that contains https://github.com/rigetti/pyquil/pull/1331, which removes the statefulness from QAM objects and offers its own handles that we could put into the ResultHandle to query later.

**Comment by kalzoo** [comment]
That release will be out next week 😃
