### ISSUE TITLE
[pytket-qiskit] AerBackend does not respect n_shots list

### ISSUE THREAD

**Issue by ss2165** [CQCL/pytket-extensions#128]
AerBackend appears to only pick one n_shots value in the new interface that allows different numbers of shots to be specified for each circuit using `process_circuits`.

Failing example: 
```python
from pytket import Circuit
from pytket.extensions.qiskit import AerBackend
b = AerBackend()
circuit = Circuit(1)
assert [len(res.get_shots()) for res in b.get_results(b.process_circuits((circuit, circuit), n_shots=(1, 2)))] == [1, 2]

```

**Comment by lmondada** [comment]
This fix was released for `pytket-qiskit` and `pytket-ionq` in versions `v0.15.1` and `v0.8.1` respectively.
