### ISSUE TITLE
[pytket-pyzx] Function tk_to_pyzx does not covert TK1(0, 0,  theta) to spiders!

### ISSUE THREAD

**Issue by RitaAhmadi** [CQCL/pytket-extensions#222]
A circuit after a round of ```PeepholeOptimise2Q()``` has rotations/gates like ```TK1(0, 0,  theta)```. ```tk_to_pyzx``` does not recognize them as ```pyzx``` gates. And I received the exception error of, line 67, ```pyzx\pyzx_convert.py```. 
Since ```TK1(a, b, c)``` is a rotation, that should not be hard to add three Euler angles instead of them or at least when only one of ```(a, b, c)``` has a non-zero value. 
(I can code them into ```pyzx_convert.py``` if no one is currently working on them! Which file in the source code contains the definition of ```TK1(a, b, c)``` gates? )

**Comment by cqc-alec** [comment]
Hi @fatimahmadi , thank you for the report. You are right, TK1 gates are missing from the pyzx conversion code, and it would definitely be useful to add them! It should be quite straightforward as they are defined in terms of Rz and Rx gates:

TK1(a, b, c) = Rz(a) Rx(b) Rz(c)

where the product is in matrix-multiplication order (i.e. the reverse of circuit order).

**Comment by fatimahmadi** [comment]
Thanks @cqc-alec Okay, is this currently a work-in-progress? I can code that, just making sure, no one is on that task! Plus, could you please let me know which file in the source code contains the definition of TK1(a, b, c) gates? ) I cannot find that in ```circuit``` module.
