### ISSUE TITLE
[pytket-qiskit] Conversion of qiskit circuit to pytket circuit with non-real angles

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-extensions#258]
It is possible to construct a circuit in qiskit which can be successfully converted with `qiskit_to_tk` to a pytket circuit, but where the pytket circuit contains invalid data. The following script (`bad.py`) illustrates this:

```python
from qiskit.opflow import PauliTrotterEvolution
from qiskit.opflow.primitive_ops import PauliSumOp
from pytket.extensions.qiskit import qiskit_to_tk
from pytket.passes import DecomposeBoxes

op = PauliSumOp.from_list([("Z", 1j)])
evolved_op = op.exp_i()
evolution_circ = PauliTrotterEvolution(reps=1).convert(evolved_op).to_circuit()

tk_circ = qiskit_to_tk(evolution_circ)

DecomposeBoxes().apply(tk_circ)

cmds = tk_circ.get_commands()
assert len(cmds) == 1
op = cmds[0].op

print(op.type)
print(op.params)
```

Output:

```
OpType.Rz
Traceback (most recent call last):
  File "bad.py", line 19, in <module>
    print(op.params)
RuntimeError: Not Implemented
```

**Comment by Roland-djee** [comment]
Any thoughts on this @cqc-alec ? What is weird is that in the former case, when the return of `get_commands()` is assigned to a variable, there is no runtime error.

**Comment by cqc-alec** [comment]
The `Not Implemented` just means that there was an invalid (non-real) parameter in the operation. TKET is correct to raise an error here (though the error message could be more helpful). The problem is that an exception should have been thrown earlier: I think it shouldn't be possible to construct such a circuit. i.e. `qiskit_to_tk` should have failed.

**Comment by cqc-alec** [comment]
Because it's not physically meaningful: U3(a,b,c) is non-unitary unless we restrict a, b and c to real values. So we should not accept them as valid parameters.

**Comment by Roland-djee** [comment]
Sure, but none of the parameters from the qiskit `U3` are complex when passed to `qiskit_to_tk`.

**Comment by Roland-djee** [comment]
Here is the output of the same script above where I print `evolution_circ` in two cases where the parameter is `1j` and `1` respectively. In both cases, the circuit parameters are identical but somehow there is an error thrown from pytket when it is complex. It returns the right value otherwise.

```python
❯ python bad.py
evolution circ
    ┌──────────────┐
q: ┤ exp(-i Z)(1) ├
   └──────────────┘
circ params [(Instruction(name='exp(-i Z)', num_qubits=1, num_clbits=0, params=[1.0]), [Qubit(QuantumRegister(1, 'q'), 0)], [])]
<tket::Circuit, qubits=1, gates=1>
[CircBox q[0];]
<class 'list'>
OpType.Rz
Traceback (most recent call last):
  File "/Users/roland/Desktop/Projects/Tket/tket-sdk/pytket/pytket-extensions/modules/pytket-qiskit/bad.py", line 30, in <module>
    print(op.params)
RuntimeError: Not Implemented
❯ python bad.py
evolution circ
    ┌──────────────┐
q: ┤ exp(-i Z)(1) ├
   └──────────────┘
circ params [(Instruction(name='exp(-i Z)', num_qubits=1, num_clbits=0, params=[1.0]), [Qubit(QuantumRegister(1, 'q'), 0)], [])]
<tket::Circuit, qubits=1, gates=1>
[CircBox q[0];]
<class 'list'>
OpType.Rz
[1.0]
```

**Comment by cqc-alec** [comment]
I don't think there is any difference in what is printed there; need to dekve further into how the operations are expanded.
Anyway, the bottom line is that `qiskit_to_tk` should reject this non-physical circuit.
