### ISSUE TITLE
[pytket-braket] Error constructing `BraketBackend` with `dm1` simulator

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-extensions#311]
Due to unsupported operation types.

**Comment by dhaycraft** [comment]
Is there any comparable operation to the depolarizing braket operation in pytket operation set?

**Comment by cqc-alec** [comment]
> Is there any comparable operation to the depolarizing braket operation in pytket operation set?

No, we cannot currently support noise channels as operations in pytket circuits.
