### ISSUE TITLE
[pytket-braket] Braket QPU device samples dimension from get_counts doesn't match input circuit qubits

### ISSUE THREAD

**Issue by dhaycraft** [CQCL/pytket-extensions#341]
When I run jobs through Rigetti Aspen-M-1 the dimension of the samples of the output is always 80.

as an example let's say I have a circuit which has 4 qubits.

The results.get_result().get_counts()

will return samples that are dimension 80
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 ..... 0 0 0 0 0 1 0 0 0]

Please let me know if this is expected behavior

Package Versions:
pytket                          1.0.1
pytket-braket                   0.17.0
amazon-braket-schemas           1.8.0
amazon-braket-sdk               1.18.0

Update: I've been running some additional problems and I believe that this issue is more pervasive than originally thought.

I have since ran problem on OQC Lucy (on Braket) as well as IonQDevice and the same issue is coming into play where the measurement counts from the task object appear to always be the size of the quantum device in terms of qubits.

**Comment by cqc-alec** [comment]
Thanks for reporting this -- it does not look like expected behaviour. I will investigate.

**Comment by dhaycraft** [comment]
I've been running some additional problems and I believe that this issue is more pervasive than originally thought.

I have since ran problem on OQC Lucy (on Braket) as well as IonQDevice and the same issue is coming into play where the measurement counts from the task object appear to always be the size of the quantum device in terms of qubits.

I'm guessing this is an issue with how pytket is submitting or converting it's circuits but I haven't got that far yet in debugging.

**Comment by dhaycraft** [comment]
I think I've pinpointed the line that's causing the issue
https://github.com/CQCL/pytket-extensions/blob/develop/modules/pytket-braket/pytket/extensions/braket/backends/braket.py#L624

**Comment by cqc-alec** [comment]
Yes, that is the line in question. I think the reason it was done like this was that some QPUs (IonQ) required the circuits to contain all qubits. But it would be better if this was hidden from the user, so that the results they get back only refer to the qubits of the original (smaller) circuit. This could potentially be done by storing the original qubits in the backend cache, and using them to reduce the results.

**Comment by dhaycraft** [comment]
Would it be fine to remove the if statement in question for Braket?

**Comment by cqc-alec** [comment]
I think that would cause errors with the IonQ backend.

**Comment by dhaycraft** [comment]
yeah you're right of course

**Comment by dhaycraft** [comment]
How do you tell which qubits are mapped to which registers on the devices?
