### ISSUE TITLE
[pytket-braket] get_compiled_circuit step adds additional qubits when mapping device for Aspen-M-1 device

### ISSUE THREAD

**Issue by dhaycraft** [CQCL/pytket-extensions#375]
Was testing out changes for #348 and found that when using get_compiled_circuit will map to more qubits than were in the original problem for Aspen-M-1 device for certain circuits. I guess this isn't super surprising since the connectivity graph is kind of sparse so any time there is dense connectivity in your circuit need to add additional bits. However this makes the results being read out from the machine a different dimension than the original logical qubits for the circuit that was compiled. Is there any sort of reasonable way to select qubits to map back to the original logical qubits or to aggregate from physical qubits?

**Comment by cqc-alec** [comment]
The mapping pass used in the default compilation sequence for `BraketBackend` is `CXMappingPass`, which can indeed make use of ancilla qubits during routing. So it is possible that the compiled circuit has more qubits than the original. However, it does not introduce measure operations on these additional qubits, so the results should have the expected dimensions. If they do not, that is probably a bug in the backend code, e.g. an incorrect assumption that all qubits are measured.

Please could you share an example to demonstrate the issue?

Thank you!

**Comment by cqc-alec** [comment]
In fact this is one of several backends where measurements are automatically applied to all qubits. This used to work OK, but since the recent changes to routing in tket it can cause problems when ancilla qubits are introduced.

**Comment by dhaycraft** [comment]
Do you have a fix in mind?

**Comment by dhaycraft** [comment]
```
qpu_device = BraketProvider(device_name = "Aspen-M-1")
c1 = Circuit(1)
c1.X(0)
c1.measure_all()
x2 = qpu_device.get_compiled_circuit(c1)
handle = qpu_device.process_circuit(x2, n_shots = 10)
```

CircuitNotValidError: Circuit with index 0 in submitted does not satisfy GateSetPredicate:{ ISWAPMax CU1 S Z H SWAP X Rx Y Ry Sdg T Tdg Rz noop U1 CX ISWAP CZ } (try compiling with backend.get_compiled_circuits first).
I'm not able to compile circuits that have

**Comment by cqc-alec** [comment]
Yes, this will be changed as part of the fix. Currently, submitted circuits may not contain measurement operations (it is assumed that all qubits are measured).

**Comment by dhaycraft** [comment]
Could you direct me to resources that could tell me how logical qubit measurements/are mapped to physical qubits?
