### ISSUE TITLE
[pytket-ionq] When low number of shots and low probability on all histogram states yields error when getting circuit_status

### ISSUE THREAD

**Issue by dhaycraft** [CQCL/pytket-extensions#381]
Circuits sometimes get all zero counts for ionq and then error out when trying to get results.

I think it's due to rounding on this [line](https://github.com/CQCL/pytket-extensions/blob/develop/modules/pytket-ionq/pytket/extensions/ionq/backends/ionq.py#L323) and all OutcomeArray counts ending up with 0 counts.

When I look at the tket_counts when I run the circuit_status function line by line before the failure I see this
tket_counts.most_common()
[(None, 10),
 (OutcomeArray([[0, 0]], dtype=uint8), 0),
 (OutcomeArray([[128,   0]], dtype=uint8), 0),
 (OutcomeArray([[64,  0]], dtype=uint8), 0),
 (OutcomeArray([[192,   0]], dtype=uint8), 0),
 (OutcomeArray([[32,  0]], dtype=uint8), 0),
 (OutcomeArray([[160,   0]], dtype=uint8), 0),
 (OutcomeArray([[96,  0]], dtype=uint8), 0),
 (OutcomeArray([[224,   0]], dtype=uint8), 0),
 (OutcomeArray([[16,  0]], dtype=uint8), 0),
.
.
.
]

Produces error while getting circuit_status for job on Ionq
```
File /opt/anaconda3/envs/quoir/lib/python3.9/site-packages/pytket/extensions/ionq/backends/ionq.py:338, in IonQBackend.circuit_status(self, handle)
    333 ppcirc = (
    334     Circuit.from_dict(ppcirc_rep) if ppcirc_rep is not None else None
    335 )
    336 if handle in self._cache:
    337     self._cache[handle].update(
--> 338         {"result": BackendResult(counts=tket_counts, ppcirc=ppcirc)}
    339     )
    340 else:
    341     self._cache[handle] = {
    342         "result": BackendResult(counts=tket_counts, ppcirc=ppcirc)
    343     }

File /opt/anaconda3/envs/quoir/lib/python3.9/site-packages/pytket/backends/backendresult.py:139, in BackendResult.__init__(self, q_bits, c_bits, counts, shots, state, unitary, density_matrix, ppcirc)
    135     if shots is not None:
    136         raise ValueError(
    137             "Provide either counts or shots, both is not valid."
    138         )
--> 139     _bitlength = next(self._counts.elements()).width
    141 if self._shots is not None:
    142     _bitlength = self._shots.width

AttributeError: 'NoneType' object has no attribute 'width'
```

Relevant Packages:
- pytket 1.1.0
- pytket-ionq 0.17.0

**Comment by cqc-alec** [comment]
If the error is coming from that line, then I think it indicates a bug at the IonQ end, since it seems it must be returning a distribution that could not have arisen in an actual run.

Could you please share (a minimal version of) the code to reproduce this?

Thanks!

**Comment by cqc-alec** [comment]
I still think this is a bug in the ionq simulator, if it returns a histogram that could never actually occur from a real device. It ought to sample from the theoretical distribution and return the resulting histogram (which will be non-uniform). I guess we need to work around it by sampling from the histogram at our end.
