### ISSUE TITLE
[pytket-braket] QPU Lucy and QPU Aspen M-1 returns incorrect dimension of results leading to out of bound when trying to get results

### ISSUE THREAD

**Issue by dhaycraft** [CQCL/pytket-extensions#382]
censored task id
{ResultHandle('some_task_from_aws_arn', '[0, 1, 2, 3, 4]', '[[2, 4], [0, 0], [1, 7], [3, 6], [4, 5]]', False, False, 'null'): {}}

File /opt/anaconda3/envs/quoir/lib/python3.9/site-packages/pytket/extensions/braket/backends/braket.py:753, in BraketBackend.circuit_status(self, handle)
    749     return CircuitStatus(StatusEnum.CANCELLED)
    750 elif state == "COMPLETED":
    751     self._update_cache_result(
    752         handle,
--> 753         _get_result(
    754             task,
    755             json.loads(target_qubits),
    756             dict(json.loads((measures))),
    757             want_state,
    758             want_dm,
    759             ppcirc,
    760         ),
    761     )
    762     return CircuitStatus(StatusEnum.COMPLETED)
    763 elif state == "QUEUED" or state == "CREATED":

File /opt/anaconda3/envs/quoir/lib/python3.9/site-packages/pytket/extensions/braket/backends/braket.py:232, in _get_result(completed_task, target_qubits, measures, want_state, want_dm, ppcirc)
    230 else:
    231     qubits_index = [measures[i] for i in target_qubits if i in measures]
--> 232     measurements = result.measurements[:, qubits_index]
    233     kwargs["shots"] = OutcomeArray.from_readouts(measurements)
    234     kwargs["ppcirc"] = ppcirc

IndexError: index 7 is out of bounds for axis 1 with size 7

```
task = AwsQuantumTask('some_aws_task', aws_session=aws_sess)
x = task.result()
x.measurements.shape
```
(1000, 7)

Results dimension should be 8 rather than 7 but are not measuring all qubits so end up coming up short some where so any time index 7 is in the circuit will fail when trying to fetch results on Lucy

**Comment by dhaycraft** [comment]
When looking at the braket backend attribute
```
braket_lucy._all_qubits
```
[0, 1, 2, 4, 6, 7]

Doesn't look like all qubits can be measured

**Comment by dhaycraft** [comment]
I also came across this on the Rigetti device although I don't have the specifics I do for Lucy at hand

**Comment by cqc-alec** [comment]
Could you please share (a minimal version of) the code to reproduce this issue? I tried to reproduce it but did not succeed.

**Comment by dhaycraft** [comment]
I think a slightly different problem than Lucy at least the device._all_qubits is appropriate length
doesn't appear to have the same qubits in all qubits as in the compiled circuit.

But above example should work to debug both.

Let me know if you need help on this.

**Comment by cqc-alec** [comment]
Hmm, I just tried this on Lucy and it seemed to work.
Are you using the released version of the pytket-braket extension (which does not yet have the latest fix), or the version on `develop` (which does)?

**Comment by dhaycraft** [comment]
I'm using `develop` I'm still getting the out of bounds on Riggetti Aspen-M-1 when I run the above code.
