### ISSUE TITLE
[pytket-ionq] Update docs or functionality for device name input for IonQBackend

### ISSUE THREAD

**Issue by dhaycraft** [CQCL/pytket-extensions#449]
IonQ device name documentation needs to be updated or function needs to be made backwards compatible.
IonQBackend documentation [here](https://cqcl.github.io/pytket-extensions/api/ionq/api.html) has "qpu' as default input however the function errors when run with that input:
```
device = IonQBackend(device_name='qpu',
                api_key=os.getenv("IONQ_QCI_API_KEY"),
                label=label)
```
File /usr/local/lib/python3.8/dist-packages/pytket/extensions/ionq/backends/ionq.py:111, in IonQBackend.__init__(self, device_name, api_key, label, _machine_debug)
    109 self._label = label
    110 self._MACHINE_DEBUG = _machine_debug
--> 111 self._backend_info = self._available_devices(self._MACHINE_DEBUG, api_key)[
    112     device_name
    113 ]
    114 self._header = self._get_header(api_key)

KeyError: 'qpu'

------------------------------------------------------

Runs when specify any of the inputs "backend":
[{'backend': 'qpu.harmony',
  'status': 'available',
  'qubits': 11,
  'average_queue_time': 10190112,
  'last_updated': 1657826102},
 {'backend': 'simulator',
  'status': 'available',
  'qubits': 19,
  'average_queue_time': 3138,
  'last_updated': 1657826102},
 {'backend': 'qpu.s11',
  'status': 'available',
  'qubits': 11,
  'average_queue_time': 10190112,
  'last_updated': 1657826102,
  'characterization_url': '/characterizations/7b50f3ea-c7f2-4e69-9b0a-8b8de515b21e'}]

**Comment by cqc-alec** [comment]
Thanks, looks like there are a couple of "qpu" options now; do you think it makes sense to have a default at all or should we just make this a required parameter?

**Comment by dhaycraft** [comment]
"qpu.harmony" and "qpu.s11" are identical. I believe that  "qpu.s11" is included for backwards compatibility. I think it would make sense to have "qpu.harmony" be the default option as it mirrors the previous functionality.
