### ISSUE TITLE
Road map for QIR support

### ISSUE THREAD

**Issue by hamidelmaazouz** [CQCL/pytket-extensions#508]
### Discussed in https://github.com/CQCL/pytket-extensions/discussions/507

<div type='discussions-op-text'>

<sup>Originally posted by **hamidelmaazouz** March 14, 2023</sup>
Hello @Roland-djee @cqc-alec,

I would like to know what the plans are for supporting more advanced QIR releases.

The QIR extension hosted at https://github.com/CQCL/pytket-qir supports only pyqir <0.7.0. Any plans for releases >= 0.7.0 and >= 0.8.0 ? If yes is somebody already working on it ? if yes when do you guys plan to release it ?

I would be happy to contribute  but don't want to start sth that is already in play.

Best,</div>

**Comment by cqc-melf** [comment]
See https://github.com/CQCL/pytket-extensions/discussions/507
