### ISSUE TITLE
`apply_qirpass()` of Pytket-qirpass generates QIR with inverted parameters

### ISSUE THREAD

**Issue by hamidelmaazouz** [CQCL/pytket-extensions#513]
Hello @Roland-djee @cqc-alec,

I am using pytket's qirpass (https://pypi.org/project/pytket-qirpass) to optimise QIR.

* How qirpass works: QIR --parse--> Circuit --transform--> Circuit --generate--> QIR

In the QIR code generation phase, parameters of the callable are inverted. For example:

```
define void @main() #0 {
entry:
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 0 to %Qubit*))
  ret void
}

declare void @__quantum__qis__h__body(%Qubit*)
```

becomes

```
define void @main() #0 {
entry:
  call void @__quantum__qis__rz__body(double 0x3FF921FB54442D18, %Qubit* null)
  call void @__quantum__qis__rx__body(double 0x3FF921FB54442D18, %Qubit* null)
  call void @__quantum__qis__rz__body(double 0x3FF921FB54442D18, %Qubit* null)
  ret void
}

declare void @__quantum__qis__rx__body(double, %Qubit*) local_unnamed_addr

declare void @__quantum__qis__rz__body(double, %Qubit*) local_unnamed_addr
```

* Where in the code this happens: the inner-loop of `compile_basic_block_ll()`. `paramreps` are listed before `argreps`:

```
        for cmd in circuit:
            op, args = cmd.op, cmd.args
            optype, params = op.type, op.params
            name, sig = tk_to_qir[optype]
            assert len(params) + len(args) == len(sig.split(", "))
            paramreps = [encode_double(param * pi) for param in params]
            argreps = [argrep(arg) for arg in args]
            bb_ll += f"  call void @{name}({', '.join(paramreps + argreps)})\n"  ## <--------
        # Write out the remaining instructions
        for instr in unknown_sub_block:
            bb_ll += str(instr) + "\n"
```

* Q1: Shouldn't the parameters be the other way round as this inversion violates the QIR spec ?
* Q2: If yes, can I expect a patch anytime soon ?

Best,

**Comment by cqc-alec** [comment]
Hi @hamidelmaazouz ,

I'm not quite sure what the bug is here. Are you saying that the qubit pointer should come before the angle parameter in (e.g.) `__quantum__qis__rz__body`?

The order here was based on that given in [this page](https://github.com/qir-alliance/qat/blob/main/targets/target_7ee0.yaml). Do you have a reference to a specification where the order is different? (If so we should definitely try to make them consistent.)

**Comment by hamidelmaazouz** [comment]
Yes, the qubit pointer should come before the angle parameter.

> Do you have a reference to a specification where the order is different?

I was referring to the new spec under development. Here's the link: https://github.com/qir-alliance/qir-spec/blob/spec_update/specification/under_development/Instruction_Set.md

But then again, qirpass seems to adhere to spec v0.1 which makes it also valid.

Are there any plans to get a jump on the new spec in the future ?

**Comment by cqc-alec** [comment]
> Yes, the qubit pointer should come before the angle parameter.
> 
> > Do you have a reference to a specification where the order is different?
> 
> I was referring to the new spec under development. Here's the link: https://github.com/qir-alliance/qir-spec/blob/spec_update/specification/under_development/Instruction_Set.md
> 
> But then again, qirpass seems to adhere to spec v0.1 which makes it also valid.
> 
> Are there any plans to get a jump on the new spec in the future ?

I see, thanks. We won't change this immediately since doing so would break some existing pipelines, but if and when the new spec is approved we will presumably have to make that change.

**Comment by hamidelmaazouz** [comment]
Thank you @cqc-alec
